@url_dev = http://localhost:3055/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 29d1c2cbe33c35869c494e2943a282f4e5705a60f952f01788927146dfcc96d5c2c6dcb4bff7bbe5b858da92126110383bec525edc61066d3be98908ca1e68af

{
    "name": "Tips Javascript",
    "email": "shoptipsjs@gmail.com",
    "password": "123456"
}

### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: 29d1c2cbe33c35869c494e2943a282f4e5705a60f952f01788927146dfcc96d5c2c6dcb4bff7bbe5b858da92126110383bec525edc61066d3be98908ca1e68af

{
    "email": "shoptipsjs@gmail.com",
    "password": "123456",
    "refreshToken": "fake-refresh-token"
}

### logout
POST {{url_dev}}/shop/logout
x-api-key: 29d1c2cbe33c35869c494e2943a282f4e5705a60f952f01788927146dfcc96d5c2c6dcb4bff7bbe5b858da92126110383bec525edc61066d3be98908ca1e68af
x-client-id: 66c198f5868978415e6e1d1c
Authorization: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2NmMxOThmNTg2ODk3ODQxNWU2ZTFkMWMiLCJlbWFpbCI6InNob3B0aXBzanNAZ21haWwuY29tIiwiaWF0IjoxNzIzOTY3NDU4LCJleHAiOjE3MjQxNDAyNTh9.QanmSbvD0OPEyxJsBbs-WsnUr8J9KqlP2X13uSN0r73oB5NSBDNggXgH8oqw16nbetqEZl7H0mhVph2Gq3t4NCG1I_OVNAmBeKCg63tC17kq54lLOj5Xy9fs-VIYqlc-gzRnbMZCkBg6GPetC7R9iDrsanVV7ec4yFwb76fy3WD-EnSt_EK5XY-tG4NxdF8g8EjeBBxTZDH6T0M54ORVgTXtJQ92YIk28l0WNx--COpXeNWQ6lJ8Gxw9adWSSZ4zvDNc9bmJsnwg6fBYOe_w8HCU2tqHMKDqmj9YiIy3NNrMD1scaOC3m-md0dHTdiDTy4v0K9qCO8lGdFy8fpNhIfPRD1XJsl_vPGupNd3r43VX8rder3yEFmoF0UrpVBzW7Rq46jsDs2qwhMxpp6A-bYnjpvRbKjded_KbGCKIdEbM_upegZrE7CULMMDKoA69agVn7cbA1Nm2NHYwOLsRPCv4RcRxBvvci6vGDZ6RYwtCPSi6_pBthTD3NUuRBCQSUEoFnZuj-0PEaV0wpAH1RUFQYoSO9FqmGRwTtrgmcU0viEMiqAw-0bz8A6AcRU0edwUKvpSY0J1DllPqbmwy6mneaZy4U8mRY1Uh7I7LaYDxRaDtnNZ-hJkYE9lnbDJvvwhVaNmxDNnbQZ0T9PVGH6i8tIP1zDATo9e7Tf9X-Qk



